version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: faustv/kittygram_backend
    env_file: .env.example
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    image: faustv/kittygram_frontend
    env_file: .env.example
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: faustv/kittygram_nginx
    env_file: .env.example
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    ports:
      - 9000:80